# Generated by Django 3.0.6 on 2021-07-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('wrongAnswer1', models.CharField(max_length=100, null=True)),
                ('wrongAnswer2', models.CharField(max_length=100, null=True)),
                ('wrongAnswer3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('givenAnswer', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=False)),
                ('quizDuration', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.QuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('quiz', models.ManyToManyField(to='Quiz.QuizDetail')),
            ],
        ),
    ]
